apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: synology-csi
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/michaelpesa/homelab-automation.git
    path: k8s/synology-csi
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: synology-csi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
